enum enum1 {
	foo = 1,
	bar,
	baz
}

message msg1 1 {
head(256):
	byte[64] bab;
	byte[64] bib;

tail:
	byte[] beb;
	string bob;
}

message msg2 2 {
head(128):
	byte[64] bab;
	int32 bib;

tail:
	byte[4] bub;
	byte beb;
	byte bhb;
	string bob;
}

message msg3 3 {head(13): byte foo;}

message msg4 4 {
head(64):
	uint64 foo;
	byte[16] arr;
tail:
	int32 baz;
	uint32[] bif;
}

message msg5 5 {
head(128):
	uint64 foo;
	tags {
		tag(1) byte[4] bab;
	}
	byte[16] arr;
tail:
	int32 baz;
	uint32[] bif;
}
